create extension if not exists "uuid-ossp";

create table if not exists public.incident_entries (
  id text primary key,
  employee_id text not null,
  employee_name text not null,
  date text not null,
  time text not null,
  category text not null,
  category_description text,
  description text not null,
  involved_parties text,
  witnesses text[] default array[]::text[],
  additional_details text,
  attachments text[] default array[]::text[],
  created_at timestamptz default now()
);

create table if not exists public.user_profiles (
  id text primary key,
  employee_id text not null unique,
  full_name text not null,
  phone_number text not null,
  default_pin text not null,
  custom_pin text,
  role text not null default 'user',
  created_at timestamptz default now()
);

create table if not exists public.incident_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 1,
  created_at timestamptz default now()
);

alter table public.incident_entries enable row level security;
alter table public.user_profiles enable row level security;
alter table public.incident_categories enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'incident_categories'
      and policyname = 'Admins can manage categories'
  ) then
    create policy "Admins can manage categories"
      on public.incident_categories
      for all
      to public
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'incident_entries'
      and policyname = 'Users can read own incidents'
  ) then
    create policy "Users can read own incidents"
      on public.incident_entries
      for select
      to public
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'incident_entries'
      and policyname = 'Users can insert own incidents'
  ) then
    create policy "Users can insert own incidents"
      on public.incident_entries
      for insert
      to public
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'incident_entries'
      and policyname = 'Users can update own incidents'
  ) then
    create policy "Users can update own incidents"
      on public.incident_entries
      for update
      to public
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'incident_entries'
      and policyname = 'Users can delete own incidents'
  ) then
    create policy "Users can delete own incidents"
      on public.incident_entries
      for delete
      to public
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users can read own profiles'
  ) then
    create policy "Users can read own profiles"
      on public.user_profiles
      for select
      to public
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users can insert own profiles'
  ) then
    create policy "Users can insert own profiles"
      on public.user_profiles
      for insert
      to public
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users can update own profiles'
  ) then
    create policy "Users can update own profiles"
      on public.user_profiles
      for update
      to public
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users can delete own profiles'
  ) then
    create policy "Users can delete own profiles"
      on public.user_profiles
      for delete
      to public
      using (true);
  end if;
end
$$;

insert into storage.buckets (id, name, public)
select 'incident-attachments', 'incident-attachments', true
where not exists (
  select 1 from storage.buckets where id = 'incident-attachments'
);
